### ISSUE TITLE
Aspect ratio of the plots is sometimes wrong

### ISSUE THREAD

**Issue by CatdBD** [benflips/nCovForecast#44] opened 2020-04-10 02:34 UTC
Seems to happen after switching from Global to State-based and back.

**Comment by CatdBD** [comment] 2020-04-10 02:36
Some examples:

![image](https://user-images.githubusercontent.com/11154277/78957154-d96d9580-7b27-11ea-8940-834126b96c37.png)

![image](https://user-images.githubusercontent.com/11154277/78957146-d70b3b80-7b27-11ea-8bd8-07a118a19435.png)

**Comment by benflips** [comment] 2020-04-10 03:05
I can't reproduce this.  Can you give me some local details: browser, OS?

**Comment by benflips** [comment] 2020-04-10 04:38
OK, I can reproduce it... sometimes.  Reload resolves it.  That's going to be tricky to find...

**Comment by CatdBD** [comment] 2020-04-12 07:30
Yeah... It's a tricky one. Sorry for pointing out a doozy haha

**Comment by CatdBD** [comment] 2020-04-12 07:30
Let me know if you still want browser and OS info :)

**Comment by melissamakin123** [comment] 2020-04-21 05:24
Fixed by #72

**Comment by melissamakin123** [comment] 2020-04-21 06:14
Reverting with https://github.com/benflips/nCovForecast/pull/73 as this made things worse (plot much wider than screen width) on mobile all the time, not just for this weird edge case.

**Comment by melissamakin123** [comment] 2020-05-13 05:48
Fixed by #105 - no longer have tabs.  Thanks @CatdBD for reporting this.

**Closed as completed by melissamakin123** 2020-05-13 05:48 UTC
